export type TripProps = {
  city: string;
  startDate: string;
  endDate: string;
  imageUrl: string;
};
export type ForecastProps = {
  datetime: string;
  conditions: string;
  tempmax: number;
  tempmin: number;
  icon: string;
};
export type WeatherProps = {
  queryCost: number;
  latitude: number;
  longitude: number;
  resolvedAddress: string;
  address: string;
  timezone: string;
  tzoffset: number;
  days: {
    datetime: string;
    datetimeEpoch: number;
    tempmax: number;
    tempmin: number;
    temp: number;
    feelslikemax: number;
    feelslikemin: number;
    feelslike: number;
    dew: number;
    humidity: number;
    precip: number;
    precipprob: number;
    precipcover: number;
    preciptype: string[];
    snow: number;
    snowdepth: number;
    windgust: number;
    windspeed: number;
    winddir: number;
    pressure: number;
    cloudcover: number;
    visibility: number;
    solarradiation: number;
    solarenergy: number;
    uvindex: number;
    severerisk: number;
    sunrise: string;
    sunriseEpoch: number;
    sunset: string;
    sunsetEpoch: number;
    moonphase: number;
    conditions: string;
    description: string;
    icon: string;
    stations: string[];
    source: string;
  }[];
};
export type ModalProps = {
  isOpen: boolean;
  onClose: () => void;
  newTrip: TripProps;
  onChange: React.Dispatch<React.SetStateAction<TripProps>>;
  onAddTrip: () => void;
};
export type CitiesProps = {
  img: string;
  cities: string;
};
